### ISSUE TITLE
Disable sanitizers in i3-gaps

### ISSUE THREAD

**Issue by DasHammett** [ChrisOboe/oboeverlay#1]
Hi, 
Thank you for making this package for Gentoo first of all.

I noticed that sanitizers are not disabled by default in your ebuild. Could you perhaps include the sanitizers removal (--disable-sanitizers) in the upcoming releases?

Failing to disable the sanitizers mkes i3 and i3bar consume increasing amounts of memory.

Please see: github.com/Airblader/i3/wiki/Compiling-&-Installing

Thank you

Kind regards,

**Comment by ChrisOboe** [comment]
thanks for the bug report. I updated the ebuild, the 4.14.1 version shouldn't build with sanitizers anymore.
