### ISSUE TITLE
polybar-3.1.0 is available

### ISSUE THREAD

**Issue by crocket** [ChrisOboe/oboeverlay#2]
Can you add polybar-3.1.0 to oboeverlay?

**Comment by ChrisOboe** [comment]
I already tried but it doesn't compile properly on my system and i didn't look further into the issue. 
But in the next few days i will take a look at it.

**Comment by ChrisOboe** [comment]
It seems polybar 3.1.0 doesn't work with with new xcb-proto versions. https://github.com/jaagr/polybar/issues/1090.
It's already fixed in git polybar but no updated polybar release yet.

**Comment by ChrisOboe** [comment]
the ebuild for 3.1.0 is added.
